### ISSUE TITLE
EXPOSED SECRET KEY

### ISSUE THREAD

**Issue by alvinphilips** [domingosjuliopinto/PythonTutorialWebsite#1]
There is a key that was exposed, which could be a security threat. I'd suggest using a combination of a .gitignore and .env file

**Comment by domingosjuliopinto** [comment]
Please tell me in which file is it expose

**Comment by domingosjuliopinto** [comment]
Please tell me in which file is the secret key exposed

**Comment by alvinphilips** [comment]
I found the aforementioned issue in [main/exp11pp/settings.py](https://github.com/domingosjuliopinto/PythonTutorialWebsite/blob/main/exp11pp/settings.py)

**Comment by domingosjuliopinto** [comment]
The issue has been sorted. Thank you for informing regarding the same
