### ISSUE TITLE
Static file directory path

### ISSUE THREAD

**Issue by joel06-dsouza** [domingosjuliopinto/PythonTutorialWebsite#2]
?: (staticfiles.W004) The directory 'C:\Users\Joel Dsouza\Downloads\PythonTutorialWebsite-main\PythonTutorialWebsite-main\static' in the STATICFILES_DIRS setting does not exist.

**Comment by domingosjuliopinto** [comment]
We have just fixed this issue. Thank you for finding it

**Comment by joel06-dsouza** [comment]
:->
